version: "3"

services:
  codegen-client:
    image: ghcr.io/curt-park/serving-codegen-gptj-triton:latest
    container_name: codegen-client
    environment:
      - TRITON_SERVER_URL=codegen-server:8001
      - GRADIO_SERVER_NAME=0.0.0.0
    ports:
      - 7860:7860
    # restart: always

  codegen-server:
    image: ghcr.io/curt-park/serving-codegen-gptj-triton:server-22.12
    container_name: codegen-server
    command: tritonserver --model-repository=/models
    shm_size: 4gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # restart: always
